export const typography = {
    fontFamily: {
        sans: '"Inter", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        mono: '"SFMono-Regular", Consolas, "Liberation Mono", monospace',
    },
    fontSize: {
        caption: '0.6875rem',
        xs: '0.75rem',
        support: '0.8125rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
    },
    lineHeight: {
        tight: '1.2',
        snug: '1.375',
        normal: '1.5',
        relaxed: '1.625',
    },
    fontWeight: {
        regular: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
        extrabold: 800,
    },
    letterSpacing: {
        normal: '0',
        label: '0.01em',
        wide: '0.025em',
        wider: '0.05em',
        category: '0.08em',
        navCategory: '0.11em',
    },
    scale: {
        display: {
            fontSize: '1.5rem',
            lineHeight: '1.2',
            fontWeight: 700,
            letterSpacing: '0',
        },
        pageTitle: {
            fontSize: '1.375rem',
            lineHeight: '1.25',
            fontWeight: 700,
            letterSpacing: '0',
        },
        sectionTitle: {
            fontSize: '1.0625rem',
            lineHeight: '1.35',
            fontWeight: 600,
            letterSpacing: '0',
        },
        cardTitle: {
            fontSize: '0.9375rem',
            lineHeight: '1.35',
            fontWeight: 600,
            letterSpacing: '0',
        },
        body: {
            fontSize: '0.875rem',
            lineHeight: '1.55',
            fontWeight: 400,
            letterSpacing: '0',
        },
        supporting: {
            fontSize: '0.8125rem',
            lineHeight: '1.45',
            fontWeight: 400,
            letterSpacing: '0',
        },
        label: {
            fontSize: '0.8125rem',
            lineHeight: '1.35',
            fontWeight: 500,
            letterSpacing: '0.01em',
        },
        table: {
            fontSize: '0.8125rem',
            lineHeight: '1.45',
            fontWeight: 400,
            letterSpacing: '0',
        },
        button: {
            fontSize: '0.875rem',
            lineHeight: '1.2',
            fontWeight: 600,
            letterSpacing: '0',
        },
        navigation: {
            fontSize: '0.875rem',
            lineHeight: '1.25',
            fontWeight: 500,
            letterSpacing: '0',
        },
        category: {
            fontSize: '0.6875rem',
            lineHeight: '1.25',
            fontWeight: 600,
            letterSpacing: '0.08em',
        },
        caption: {
            fontSize: '0.75rem',
            lineHeight: '1.35',
            fontWeight: 400,
            letterSpacing: '0',
        },
    },
} as const;

export type TypographyToken = typeof typography;
